AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # Two public subnets, where containers can have public IP addresses
  PublicSubnetOne:
    DependsOn: VPC
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: { Ref: "AWS::Region" }
      VpcId: !Ref "VPC"
      CidrBlock: "10.0.0.0/24"
      MapPublicIpOnLaunch: true
